### ISSUE TITLE
Screenshots for README

### ISSUE THREAD

**Issue by yaa110** [yaa110/Effects-Pro#1]
![rsz_1screenshot](https://cloud.githubusercontent.com/assets/3187511/5158844/bc02e30c-7361-11e4-8563-d3f87d915b6e.jpg)
![rsz_screenshot_1](https://cloud.githubusercontent.com/assets/3187511/5158851/e8af935a-7361-11e4-9576-d14cd78eeaee.jpg)
![rsz_screenshot_2](https://cloud.githubusercontent.com/assets/3187511/5158846/bc56102c-7361-11e4-8f91-20b9d2fbc1d7.jpg)
![rsz_screenshot_3](https://cloud.githubusercontent.com/assets/3187511/5158847/bc6150f4-7361-11e4-88d8-1789821e50fc.jpg)

**Comment by pimfox** [comment]
this is nice

**Comment by ChuwxNTC** [comment]
All of things image effect was processing in pixel. It take a long time for big image

**Comment by JavadShaahin** [comment]
@javadshaahin

azizam ye pm behem bede to telegram karet daram ye proje daram mikham dar moredesh age ghabel bedoni harf bezanim mamnonam <3
